### ISSUE TITLE
it is not indenting correctly

### ISSUE THREAD

**Issue by avelino** [yamadashy/slack-channels-grouping#32]
printscreen with a case that is not indenting correctly 
<img width="247" alt="Screenshot 2023-01-31 at 08 27 30" src="https://user-images.githubusercontent.com/31996/215748428-da200cdd-f113-4424-b6d0-d6fc1cfbf616.png">

**Comment by yamadashy** [comment]
Sorry, my reply is late.
Thank you for the issue.

This seems to happen when Chrome is updated or otherwise restarted.
I will figure out how to fix it.

**Comment by yamadashy** [comment]
@avelino 
Fixed version 1.0.32 is now available.

Thank you for your report and using this extension!
